"""Test category-to-entity-type keyword mapping coverage."""
import pandas as pd

CATEGORY_ENTITY_MAP = {
    # =========================================================================
    # PERSON — Categories where the answer is likely a person
    # =========================================================================
    "PERSON": [
        # Direct role/title keywords
        "president", "vice president", "first lad",
        "hail to the chief",  # Jeopardy euphemism for presidents
        "author", "writer", "novelist", "playwright", "dramatist",
        "poet",
        "actor", "actress",
        "composer", "conductor", "musician", "singer", "vocalist", "rapper",
        "comedian", "comedienne",
        "scientist", "physicist", "chemist", "biologist", "naturalist",
        "explorer", "adventurer", "navigator", "exploration",
        "leader", "ruler", "monarch", "king", "queen", "prince", "princess",
        "emperor", "empress", "pharaoh", "czar", "tsar",
        "dictator", "tyrant",
        "governor", "senator", "congressman", "politician", "statesman",
        "general", "admiral", "commander", "officer",
        "pope", "cardinal", "bishop", "rabbi", "imam", "priest",
        "saint",
        "philosopher", "theologian",
        "mathematician",
        "architect",
        "inventor",
        "chef", "sommelier",
        "astronaut", "cosmonaut",
        "pilot", "aviator",
        "athlete", "champion", "olympian",
        "designer",
        "photographer",
        "sculptor",
        "painter",
        "choreographer",
        "director",
        "producer",
        "journalist", "reporter", "editor", "columnist", "anchor",
        "spy", "spies", "pirate",
        "philanthropist", "billionaire", "mogul", "tycoon",
        "entrepreneur",
        "knight",
        # Collective people categories
        "people", "person", "personality", "personalities",
        "famous", "notable", "notorious", "historic name", "historic people",
        "celebrity", "celebrities", "celeb",
        "biograph", "autobiograph",
        "royalty", "nobility", "aristocra",
        "nobel",
        "hall of fame", "halls of fame",
        "women in history", "women in sport", "famous women",
        "women of", "historic women", "quotable women",
        "women on", "female first",
        "men in history",
        "who said", "who wrote", "who played", "who sang", "who was",
        "who is", "who are",
        # Name-pattern categories
        "first name", "last name", "middle name", "nickname",
        "pen name", "a.k.a", "aka",
        "namesake", "name's the same",
        "names in the news", "names in ",
        "born & died", "birthplace",
        "better known as",
        "lesser-known name",
        # Specific person names as categories
        "lincoln", "napoleon", "churchill", "gandhi", "einstein",
        "cleopatra", "caesar", "alexander the great",
        "hemingway", "twain", "dickens", "poe",
        "beethoven", "mozart", "bach",
        "elvis", "sinatra", "beatles",
        "oprah", "martha stewart",
        "picasso", "rembrandt", "van gogh", "michelangelo", "da vinci",
        "columbus", "magellan",
        "darwin", "newton", "galileo", "copernicus",
        "disney",
        "kennedy", "roosevelt", "jefferson", "hamilton", "washington",
        "shakespeare",  # Usually about the person or his works — PERSON for the category
        "gilbert & sullivan", "alice in wonderland",
        # Occupations as categories
        "occupation", "job", "career", "profession",
        # Family/relationship categories
        "family", "families", "relative", "sibling", "twin", "couple",
        "mother", "father", "son", "daughter", "brother", "sister",
        "contemporary", "contemporaries",
        # Misc people categories
        "ladies", "gentlemen",
        "firsts",  # "Women's firsts", "Famous firsts" — who did something first
        "pioneer",
        "hero", "heroine",
        "earl", "duke", "baron", "lord",
        "ranks & titles",
    ],

    # =========================================================================
    # GPE — Geopolitical entities: countries, states, cities, capitals
    # =========================================================================
    "GPE": [
        # Direct geography keywords
        "countr",
        "state", "province", "territory",
        "city", "cities", "town", "village",
        "capital",
        "geograph",
        "nation",
        "place name",
        # Map/travel categories
        "on the map", "around the world", "travel", "tourism", "tourist",
        "where am i", "where is", "where in",
        "u.s.a", "usa", "americana",
        "flag",
        "airport",
        "u.s. place", "place names",
        # Continental/regional categories
        "europe", "asia", "africa", "south america", "north america",
        "central america",
        "middle east", "far east", "pacific", "caribbean", "mediterranean",
        "hemisphere", "around the usa",
        "the south", "the midwest", "the west",
        "down under",
        # Specific country/region names as categories
        "australia", "canada", "mexico", "brazil", "argentina", "chile",
        "peru", "colombia", "venezuela", "cuba", "jamaica", "haiti",
        "puerto rico",
        "england", "scotland", "wales", "ireland",
        "france", "germany", "italy", "spain", "portugal", "netherlands",
        "belgium", "switzerland", "austria", "poland", "hungary", "czech",
        "romania", "ukraine", "sweden", "norway", "denmark", "finland",
        "greece", "turkey",
        "russia", "china", "japan", "korea", "india", "pakistan",
        "thailand", "vietnam", "indonesia", "philippines", "malaysia",
        "singapore", "hong kong", "taiwan",
        "egypt", "israel", "iran", "iraq", "saudi", "morocco",
        "kenya", "nigeria", "ethiopia", "south africa", "ghana", "tanzania",
        "congo", "zimbabwe",
        "new zealand",
        "soviet union",
        "brittany",
        # US state names as categories
        "alabama", "alaska", "arizona", "arkansas", "california", "colorado",
        "connecticut", "delaware", "florida", "georgia", "hawaii", "idaho",
        "illinois", "indiana", "iowa", "kansas", "kentucky", "louisiana",
        "maine", "maryland", "massachusetts", "michigan", "minnesota",
        "mississippi", "missouri", "montana", "nebraska", "nevada",
        "new hampshire", "new jersey", "new mexico", "new york",
        "north carolina", "north dakota", "ohio", "oklahoma", "oregon",
        "pennsylvania", "rhode island", "south carolina", "south dakota",
        "tennessee", "texas", "utah", "vermont", "virginia",
        "west virginia", "wisconsin", "wyoming",
        # Major city names as categories
        "new york city", "los angeles", "chicago", "boston", "san francisco",
        "philadelphia", "washington d.c", "new orleans", "miami", "seattle",
        "denver", "dallas", "houston", "atlanta", "detroit", "pittsburgh",
        "st. louis", "minneapolis", "baltimore", "cleveland", "cincinnati",
        "nashville", "memphis", "las vegas", "phoenix", "portland",
        "london", "paris", "rome", "berlin", "moscow", "tokyo",
        "beijing", "vienna", "prague", "amsterdam", "budapest",
        "venice", "florence", "barcelona", "dublin", "edinburgh",
        "istanbul", "cairo", "jerusalem", "mumbai", "delhi",
        "sydney", "toronto", "montreal", "vancouver",
        # County/district
        "county", "counties", "borough", "district",
        # Map features
        "map",
        "border",
    ],

    # =========================================================================
    # LOC — Physical geographic features (not political boundaries)
    # =========================================================================
    "LOC": [
        "island",
        "river",
        "lake",
        "ocean",
        "mountain", "mount ",
        "sea ",
        "seas",
        "body of water", "bodies of water",
        "waterway", "water ",
        "peninsula",
        "continent",
        "forest",
        "volcano",
        "desert",
        "canyon",
        "cape",
        "reef",
        "glacier",
        "valley",
        "strait",
        "channel",
        "bay ",
        "bays",
        "gulf",
        "harbor", "harbour",
        "waterfall",
        "cave", "cavern",
        "peak",
        "plateau",
        "the earth",
        "swamp", "marsh", "wetland",
        "prairie", "plain", "steppe", "tundra", "savanna",
        "national park",
        "landform",
        "creek", "brook", "stream",
        "canal",
    ],

    # =========================================================================
    # ORG — Organizations, companies, institutions, teams
    # =========================================================================
    "ORG": [
        "business", "corporation", "corporate", "company", "companies",
        "brand", "brand name",
        "industry",
        "college", "universit",
        "school",
        "team",
        "organization",
        "magazine", "newspaper", "journal",
        "airline",
        "bank", "banking",
        "museum",
        "library", "libraries",
        "hospital",
        "foundation",
        "academy",
        "institut",
        "agency", "agencies",
        "club",
        "league",
        "association",
        "fraternity", "sorority",
        "military",
        "army", "navy", "marines", "air force", "coast guard",
        "nfl", "nba", "mlb", "nhl", "fifa", "nascar",
        "store", "shop",
        "restaurant",
        "hotel",
        "church",
        "denomination",
        "united nations", "u.n.",
        "congress",
        "supreme court",
        "cabinet",
        "white house",
        "government", "politic",
        "publish", "publisher",
        "advertis",
        "stock symbol", "stock market", "wall street",
        "fortune 500",
        "startup",
        "labor union",
        "circus",
        "democrat", "republican",
    ],

    # =========================================================================
    # WORK_OF_ART — Books, films, shows, songs, paintings, plays, operas
    # =========================================================================
    "WORK_OF_ART": [
        "book", "novel", "novella",
        "film", "movie", "cinema",
        "play",
        "song", "hit song", "hit single",
        "painting", "mural", "fresco",
        "opera",
        "tv ", "tv show", "television",
        "musical",
        "ballet",
        "poem",
        "poetry",
        "theater", "theatre",
        "lyric",
        "fiction",
        "literature",
        "lit ",  # "kiddie lit", "american lit", "brit lit"
        "lit-",  # "lit-pourri"
        "broadway",
        "oscar", "emmy", "grammy", "tony award", "pulitzer",
        "golden globe",
        "bestseller", "best seller", "best-seller",
        "sitcom",
        "cartoon", "animated",
        "comic", "the funnies",
        "manga", "anime",
        "video game",
        "game show",
        "documentary",
        "sculpture",
        "photograph",
        "soundtrack", "score",
        "album",
        "sequel", "prequel", "remake", "adaptation", "screenplay",
        "series",
        "classic film", "classic movie",
        "fairy tale", "fable", "nursery rhyme",
        "short stor",
        "masterpiece",
        "drama",
        "mystery", "mysteries",
        "science fiction", "sci-fi",
        "fantasy",
        "romance",
        "thriller",
        "horror",
        "western",
        "the silver screen",
        "pop culture",
        "the screen", "big screen", "small screen",
        "literary character", "fictional character",
        "literary title", "literary first line", "literary allusion",
        "literary setting", "literary quote", "literary term",
        "literary award", "literary before",
        "from page to screen",
        "first lines",
        "reality tv",
        "golden oldies",
        "rock ", "jazz", "rock & roll", "rock 'n", "rock n",
        "the beatles",  # category about Beatles works
        "essay",
        "cliffs notes",
        "children's lit",
        "kiddie lit", "kiddy lit", "kid stuff",
        "nonfiction",
    ],

    # =========================================================================
    # EVENT — Wars, battles, historical events, ceremonies
    # =========================================================================
    "EVENT": [
        "war",
        "battle",
        "revolution",
        "rebellion", "revolt", "uprising",
        "civil war",
        "olymp",
        "world cup",
        "world series",
        "super bowl",
        "treaty", "treaties",
        "inaugur",
        "election", "elections",
        "coronation",
        "disaster",
        "scandal",
        "assassination",
        "trial",
        "expedition",
        "crusade",
        "siege",
        "campaign",
        "armistice", "surrender",
        "the depression", "great depression",
        "cold war",
        "space race",
        "gold rush",
        "prohibition",
        "the plague", "pandemic", "epidemic",
        "world war",
        "ceremony", "ceremonies",
        "the renaissance",
        "current events", "in the news",
        "annual event",
        "world event",
        "historic document",
    ],

    # =========================================================================
    # NORP — Nationalities, religions, ethnic groups, political groups
    # =========================================================================
    "NORP": [
        # Nationality adjectives
        "british", "english",
        "french", "german", "italian", "spanish", "portuguese",
        "dutch", "belgian", "swiss", "austrian",
        "swedish", "norwegian", "danish", "finnish", "icelandic",
        "polish", "hungarian", "czech", "romanian", "bulgarian",
        "russian", "ukrainian", "serbian", "croatian", "bosnian",
        "greek", "turkish",
        "american",
        "canadian", "mexican", "brazilian", "argentinian",
        "cuban", "jamaican", "haitian",
        "african",
        "asian", "chinese", "japanese", "korean", "vietnamese",
        "thai", "indian", "pakistani",
        "indonesian", "filipino", "malaysian",
        "arab", "persian", "iranian", "iraqi",
        "israeli", "palestinian",
        "egyptian",
        "australian",
        "irish", "scottish", "welsh",
        "latin",
        "european",
        "roman",
        "norse", "viking",
        "celtic",
        "native american", "american indian",
        "aboriginal", "indigenous",
        # Religious groups
        "religion", "religious",
        "bible", "biblical",
        "christian", "christianity",
        "jewish", "judaism", "hebrew",
        "islam", "muslim",
        "catholic", "protestant",
        "buddhist", "buddhism",
        "hindu", "hinduism",
        "quaker", "amish", "mennonite",
        "orthodox",
        "evangelical",
        "shinto",
        # Mythological/cultural groups
        "myth", "mythology",
        # Ethnic/cultural identifiers
        "ethnic",
        "tribal",
        "black america",
        "hispanic",
        "incas", "aztec", "maya",
    ],

    # =========================================================================
    # CONCEPT — Science, vocabulary, food, animals, inventions, etc.
    # =========================================================================
    "CONCEPT": [
        # Sciences
        "science", "scientific",
        "chemistry", "chemical",
        "physics",
        "biology", "biological",
        "zoology", "zoological",
        "botan",
        "ecology", "ecological",
        "geology", "geological",
        "astronomy", "astronomical",
        "astrology",
        "math", "algebra", "geometry", "calculus", "trigonometry",
        "weather", "meteorolog", "climate",
        "marine biology", "oceanograph",
        # Natural world
        "element",
        "mineral",
        "metal",
        "gem", "jewel",
        "flower",
        "tree",
        "fruit",
        "vegetable",
        "herb", "spice",
        "plant",
        "insect", "bug",
        "bird",
        "fish",
        "reptile",
        "amphibian",
        "mammal",
        "dinosaur",
        "animal",
        "nature",
        "environment",
        "conservation",
        "wildlif",
        "dog", "cat",
        "horse",
        "pet",
        # Human body & health
        "anatomy", "anatomical",
        "body", "the body",
        "bone", "skeleton",
        "brain",
        "heart",
        "muscle",
        "blood",
        "medicine", "medical",
        "health", "healthy",
        "disease", "illness", "sickness",
        "surgery", "surgical",
        "nutrition", "diet", "vitamin",
        "first aid",
        "drug", "pharmac",
        # Food & drink
        "food",
        "drink", "beverage",
        "potable",
        "cooking", "baking",
        "recipe",
        "cuisine",
        "wine", "beer", "cocktail", "whiskey", "bourbon", "vodka",
        "bread", "cheese", "chocolate", "dessert", "sweet", "candy",
        "sauce",
        "nut",
        # Technology & engineering
        "technology", "technological",
        "computer", "computing",
        "internet", "website", "cyber", "digital", "online",
        "software", "hardware",
        "robot", "artificial intelligence",
        "engineering",
        "invention",
        # Transport
        "automobile", "auto",
        "transport", "transportation",
        "ship", "boat", "vessel",
        "aircraft", "airplane", "aviation",
        "train", "railroad", "railway",
        "vehicle",
        "highway", "road",
        "bridge",
        # Law & governance
        "law",
        "legal",
        "court",
        "constitution", "amendment",
        "bill of rights",
        # Economics & finance
        "economic", "economy",
        "finance", "financial",
        "stock",
        "currency", "money", "coin",
        "trade",
        "tax",
        # Social sciences
        "psychology", "psychological",
        "sociology", "sociological",
        "anthropology",
        "archaeolog",
        "philosophy", "philosophical",
        "logic",
        "ethic",
        # Language & words
        "language",
        "word",
        "vocabulary", "vocab",
        "dictionary",
        "grammar", "grammatical",
        "spelling",
        "slang",
        "idiom",
        "proverb",
        "phrase",
        "saying",
        "cliche",
        "quote", "quotation",
        "foreign phrase",
        "etymology",
        "eponym",
        "definition",
        # Architecture & structures
        "architecture", "architectural",
        "building",
        "tower",
        "castle", "palace", "fortress",
        "cathedral", "temple", "mosque", "synagogue",
        "monument", "memorial", "landmark",
        "statue",
        # Domestic life
        "fashion", "clothing", "fabric", "textile",
        "sewing", "knitting",
        "furniture",
        "house", "home",
        "kitchen",
        "garden", "gardening",
        "room",
        # Sports (the concept/sport itself)
        "sport",
        "baseball",
        "football",
        "basketball",
        "tennis",
        "golf",
        "soccer",
        "hockey",
        "boxing",
        "wrestling",
        "swimming",
        "skiing",
        "rugby",
        "racing",
        "track and field",
        "martial art",
        # Leisure & games
        "game", "gaming",
        "toy",
        "hobby", "hobbies",
        "puzzle",
        "gambling", "casino", "poker",
        "card",
        # Space & astronomy
        "space",
        "planet",
        "moon",
        "solar",
        "star",
        "constellation",
        "comet", "asteroid",
        "galaxy",
        # Color & design
        "color", "colour",
        "design",
        # History (general)
        "history", "historical",
        "century",
        "decade",
        "ancient",
        "medieval", "middle ages",
        "modern",
        "colonial",
        "old west", "frontier",
        "the 19", "the 18", "the 17", "the 16",
        "the '", "the 20",
        # Religion concepts (the ideas, not the group)
        "testament",
        "genesis", "exodus",
        "psalm",
        "superstition",
        # Symbols & measurement
        "sign", "symbol",
        "weight", "measure",
        "unit",
        "number",
        "calendar", "month",
        "time",
        # Communication
        "communication",
        "radio",
        "telephone",
        "telegraph",
        "mail", "postal",
        "stamp",
        # Agriculture
        "agriculture", "agricultural",
        "farm", "farming",
        "crop",
        "harvest",
        # Holidays (the concept)
        "holiday", "observance",
        # Education (concept)
        "education",
        # Misc cultural concepts
        "etiquette", "manner", "custom",
        "weapon", "gun", "sword", "bomb", "artillery",
        "medal", "decoration", "award", "honor",
        "dance",
        "art",
        "music",
        "photography",
        "jewelry",
        "leather", "silk", "wool", "cotton",
        "paint",
        "ceramic", "pottery",
        "glass",
        "printing",
        "industry",
        # Record / fact categories
        "guinness", "record",
        "world facts", "facts & figures", "it's a fact",
        "social studies",
        # Abbreviations & linguistics
        "abbreviat", "abbrev", "acronym", "initial",
        "homophone", "homonym", "heteronym",
        "antonym", "synonym",
        "prefix", "suffix",
        "adjective", "adverb", "verb", "noun",
        "alliteration",
        "anagram",
        "palindrome",
        "spelling",
        "oxymoron",
        "portmanteau",
        "contronym",
        "multiple meaning", "double meaning", "more than one meaning",
        # Miscellaneous knowledge categories
        "-olog",  # -ologies
        "phobia",
        "energy",
        "container",
        "perfume", "cosmetic",
        "heraldry",
        "occult", "magic",
        "wedding",
        "angel",
        "the universe",
        "collectible", "antique",
        "tool",
        "snake",
        "rodent",
        "fitness", "exercise",
        "hat",
        "cereal",
        "ice cream",
        "dining",
        "breakfast",
        "mortal matter",
        "birthstone",
        "feathered friend",
        # Potpourri / catch-all
        "potpourri", "hodgepodge", "grab bag", "leftovers",
        "odds & ends", "this & that", "pot luck", "trivia",
        "general knowledge", "miscellaneous", "miscellany",
        "goulash",
        "common bonds",
        "stupid answer",
        # Wordplay/game mechanic categories (answers are still cultural knowledge)
        "before & after", "before, during & after",
        "letter perfect",
        "double talk", "double double",
        "add a letter",
        "same first & last",
        "missing link",
        "quasi-related",
        "alphabetically",
        "which came first",
        "put 'em in order",
        "not to be confused",
        "3 of a kind", "trios",
        "overlaps",
        "role in common",
        # Quotation-mark letter categories: "G" WHIZ, "V"OCABULARY, etc.
        # These are general knowledge with a letter constraint
        "\" whiz", "\"g\"", "\"v\"", "\"p\"", "\"c\"", "\"w\"",
        "\"d\"", "\"b\"", "\"s\"", "\"a\"", "\"f\"", "\"t\"",
        "\"e\"", "\"r\"", "\"m\"", "\"n\"", "\"l\"", "\"h\"",
        "\"i\"", "\"j\"", "\"k\"", "\"o\"", "\"q\"", "\"u\"",
        "\"x\"", "\"y\"", "\"z\"",
        # Additional specific patterns
        "labor",
        "crime", "punishment",
        "park",  # parks (as places/concept)
        "wild west",
        "psych",
        "beastly expression",
        "simile",
        "slogan",
        "heloise",
        "foreign exchange",
        "sloganeering",
        "discovery", "discoveries",
        "edible", "incredible edible",
        "invertebrate",
        "ghost",
        "pop quiz",
        "group",
        "title",
        "wood",
        "how to",
        "day of the week", "days of the week",
        "car ",
        "cars",
        "declaration of independence",
        "the short form",
        "grave matter", "final resting",
        "bottoms up",
        "new to the oed",
        "the largest",
        "pop quiz",
        "track & field", "track and field",
        "on the go",
        "alphabet soup",
        "double letters",
        "ends in",
        "begins with", "begins & ends", "starts with",
        "brit lit",
        "women",  # standalone women category
        "tv",  # standalone "TV" (2-letter)
        "misc",  # misc., miscellany
        "year categories",
    ],
}


# ---- Test coverage ----
df = pd.read_csv(
    "data/jeopardy_clue_dataset/combined_season1-41.tsv",
    sep="\t",
    low_memory=False,
)
all_cats = df["category"].unique()
lower_cats = [c.lower() for c in all_cats]
n = len(lower_cats)

# Count per-type coverage (a category can match multiple types)
type_counts = {}
classified = set()
for entity_type, keywords in CATEGORY_ENTITY_MAP.items():
    matched = set()
    for i, c in enumerate(lower_cats):
        for kw in keywords:
            if kw in c:
                matched.add(i)
                classified.add(i)
                break
    type_counts[entity_type] = len(matched)

print(f"Coverage analysis across {n:,} unique categories:")
print(f"{'Entity Type':15s} {'Matched':>10s} {'%':>8s}")
print("-" * 35)
for etype, count in sorted(type_counts.items(), key=lambda x: -x[1]):
    print(f"{etype:15s} {count:>10,} {count/n*100:>7.1f}%")

print("-" * 35)
print(f"{'Total (union)':15s} {len(classified):>10,} {len(classified)/n*100:>7.1f}%")
print(f"{'Unclassified':15s} {n-len(classified):>10,} {(n-len(classified))/n*100:>7.1f}%")

# Multi-match count
multi = 0
for i, c in enumerate(lower_cats):
    types_matched = []
    for entity_type, keywords in CATEGORY_ENTITY_MAP.items():
        for kw in keywords:
            if kw in c:
                types_matched.append(entity_type)
                break
    if len(types_matched) > 1:
        multi += 1
print(f"\nCategories matching multiple types: {multi:,} ({multi/n*100:.1f}%)")

# Clue-weighted coverage
cat_sizes = df.groupby("category").size()
total_clues = len(df)
classified_clues = 0
for cat in all_cats:
    c = cat.lower()
    for entity_type, keywords in CATEGORY_ENTITY_MAP.items():
        if any(kw in c for kw in keywords):
            classified_clues += cat_sizes[cat]
            break

print(f"\nClue-weighted coverage: {classified_clues:,} / {total_clues:,} = {classified_clues/total_clues*100:.1f}%")
